### ISSUE TITLE
Random RunTime Error: canvas: trying to use a recycled bitmap

### ISSUE THREAD

**Issue by christianvina** [wunderlist/android-sliding-layer-lib#6]
Hello,

I finally got runing the sliding layer on my app. It was an API level issue, i was using 4.2.... Using 4.1 the problem was solved...

Now my problem is that when i slide-in and slide-out the layer, i get a random runtime exception that indicates the following... Can you help me out?

java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@40db6420

04-23 12:49:59.658: E/AndroidRuntime(28582):    at android.graphics.Canvas.throwIfRecycled(Canvas.java:1026)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at android.graphics.Canvas.drawBitmap(Canvas.java:1065)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at android.view.View.draw(View.java:13625)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at android.view.ViewGroup.drawChild(ViewGroup.java:2928)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2797)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at android.view.View.draw(View.java:13594)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at android.view.ViewGroup.drawChild(ViewGroup.java:2928)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2797)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at android.view.View.draw(View.java:13594)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at android.view.ViewGroup.drawChild(ViewGroup.java:2928)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2797)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at android.view.View.draw(View.java:13715)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at android.view.View.draw(View.java:13596)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at android.view.ViewGroup.drawChild(ViewGroup.java:2928)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2797)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at android.view.View.draw(View.java:13715)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at android.widget.FrameLayout.draw(FrameLayout.java:467)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at android.view.View.draw(View.java:13596)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at android.view.ViewGroup.drawChild(ViewGroup.java:2928)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2797)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at android.view.View.draw(View.java:13594)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at android.view.ViewGroup.drawChild(ViewGroup.java:2928)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2797)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at android.view.View.draw(View.java:13715)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at android.widget.FrameLayout.draw(FrameLayout.java:467)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2211)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:2281)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at android.view.ViewRootImpl.draw(ViewRootImpl.java:2177)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2045)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1854)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:989)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4351)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at android.view.Choreographer.doCallbacks(Choreographer.java:562)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at android.view.Choreographer.doFrame(Choreographer.java:532)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at android.os.Handler.handleCallback(Handler.java:725)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at android.os.Handler.dispatchMessage(Handler.java:92)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at android.os.Looper.loop(Looper.java:137)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at android.app.ActivityThread.main(ActivityThread.java:5041)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at java.lang.reflect.Method.invokeNative(Native Method)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at java.lang.reflect.Method.invoke(Method.java:511)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
04-23 12:49:59.658: E/AndroidRuntime(28582):    at dalvik.system.NativeStart.main(Native Method)

**Comment by nikunjparadva** [comment]
solved it @JlUgia  
by adding `android:hardwareAccelerated="true"`

Thanks man

**Comment by JlUgia** [comment]
This one since it does not seem actionable anymore.
Good to be closed @aconsuegra .
